name: Test Blockhouse Download

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Block-House-Seite abrufen
        run: |
          curl -L "https://www.block-house.de/speisekarte/lunch-time/" -o blockhouse.html
          grep -i "Aktuelle Lunch Time Gerichte" blockhouse.html
